### ISSUE TITLE
General off-chain code

### ISSUE THREAD

**Issue by zlonast** [zkFold/zkfold-ethereum#20]
- [ ] https://github.com/zkFold/zkfold-ethereum/issues/13 (send requests to ethereum)
- [ ] https://github.com/zkFold/zkfold-ethereum/issues/14 (creates data input or witness for contract)
- [ ] https://github.com/zkFold/zkfold-ethereum/issues/15 (rest json api)
- [ ] https://github.com/zkFold/zkfold-ethereum/issues/16 (sync tx commits L2 and L1)
